#!/usr/bin/env bash
# Alpha 29: build the shippable playground artifact (niko2_bundle.js).
#
# What it does:
#   1. Zips niko2/**/*.py (no __pycache__) + niko2/stdlib/*.niko into niko2.zip.
#   2. Base64-encodes the zip.
#   3. Writes niko2_bundle.js defining:
#        - const NIKO2_ZIP_B64 = "..."   (the compiler, unpacked in Pyodide)
#        - const NIKO_EXAMPLES = {...}   (the examples/*.niko texts, keyed by
#          filename without extension)
#
# The examples are embedded at build time (not fetched) because fetch()
# fails on file:// pages, and the playground must work from file://.
#
# The generated niko2_bundle.js is the shippable artifact: commit it, and the
# page works with zero build tooling on the reader's side. Re-run this script
# whenever niko2/ or examples/*.niko change.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$HERE/niko2_bundle.js"
TMPZIP="$(mktemp /tmp/niko2_playground_XXXXXX.zip)"
trap 'rm -f "$TMPZIP"' EXIT

python3 - "$ROOT" "$TMPZIP" <<'PYEOF'
import sys, zipfile
from pathlib import Path

root = Path(sys.argv[1])
out = sys.argv[2]
pkg = root / "niko2"

def wanted(p: Path) -> bool:
    if "__pycache__" in p.parts:
        return False
    if p.suffix == ".py":
        return True
    # stdlib sources ship as .niko; nothing else under niko2/ is .niko
    return p.suffix == ".niko" and p.parent.name == "stdlib"

files = sorted(p for p in pkg.rglob("*") if p.is_file() and wanted(p))
if not files:
    sys.exit("no niko2 sources found under " + str(pkg))
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for p in files:
        z.write(p, p.relative_to(root))
print(f"zipped {len(files)} files")
PYEOF

ZIPSIZE=$(stat -c%s "$TMPZIP")
B64=$(base64 -w0 "$TMPZIP")
B64LEN=${#B64}

# Emit the bundle. Examples are embedded as a JS object; keys are the
# filename stems (hello, fibonacci, ...).
{
    printf '// GENERATED by examples/playground/build.sh -- do not edit by hand.\n'
    printf '// Rebuild with: cd examples/playground && ./build.sh\n'
    printf '// Contents: base64 of niko2.zip (the Niko 2 compiler, %s bytes zipped)\n' "$ZIPSIZE"
    printf '// plus the embedded example programs (fetch() is unavailable on file://).\n'
    printf 'const NIKO2_ZIP_B64 = "%s";\n' "$B64"
    printf 'const NIKO_EXAMPLES = {\n'
    first=1
    for f in "$HERE"/examples/*.niko; do
        name="$(basename "$f" .niko)"
        # JSON-encode the file text with python (handles quotes/newlines).
        jsontxt="$(python3 -c 'import json,sys; print(json.dumps(open(sys.argv[1], encoding="utf8").read()))' "$f")"
        if [ "$first" -eq 1 ]; then first=0; else printf ',\n'; fi
        printf '  %s: %s' "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$name")" "$jsontxt"
    done
    printf '\n};\n'
} > "$OUT"

OUTSIZE=$(stat -c%s "$OUT")
echo "zip: ${ZIPSIZE} bytes (target < 256000)"
echo "niko2_bundle.js: ${OUTSIZE} bytes"
if [ "$ZIPSIZE" -gt 256000 ]; then
    echo "WARNING: zip exceeds the 250 KB target" >&2
fi
